### ISSUE TITLE
Map over all 120 consumers

### ISSUE THREAD

**Issue by nhc** [parisdafermos/test#1]
https://github.com/parisdafermos/test/blob/a399ffbe000ad3a6d1685272aad03d6d7433fb04/src/App.js#L29

Paris we talked yesterday about getting all 120 records out of the json. 

To get all consumers please user this (one of a few ways) 

```typescript
let consumers = data.locations.map((location) => location.consumers).flat();
```

I hope thats helpful

**Comment by parisdafermos** [comment]
fixed
